services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - mongodb
  mongodb: 
    image : mongo
    restart : always
    environment :
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: knuipalab
    volumes:
      - .dbdata:/data/db
    ports:
     - 27017:27017 

      