services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - innerNetwork
    depends_on:
      - mongodb
  mongodb: 
    image : mongo
    restart : always
    environment :
      MONGO_INITDB_ROOT_USERNAME: knuipalab
      MONGO_INITDB_ROOT_PASSWORD: knuipalab418
    networks:
      - innerNetwork
    ports:
     - 27017:27017 

networks:
  innerNetwork:
    driver: bridge
      