spring:
  profiles:
    default: local # 기본 환경을 local
    include: oauth

  data:
    mongodb:
      host: mongodb  #local에서는 'localhost', docker server에서는 'mongodb'로 설정
      port: 27017
      database: DSMP
      authentication-database: admin
      username: knuipalab
      password: knuipalab418
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      file-size-threshold: #임시 파일을 만드는 파일 사이즈 기준
      location:  #임시 저장 경로
      max-file-size: #파일 최대 크기
      max-request-size: #요청 당 최대 파일 크기
---
spring:
  config:
    activate:
      on-profile: prod
hostLocation : imdc.hopto.org
---
spring:
  config:
    activate:
      on-profile: local
hostLocation : localhost
