spring:
  profiles:
    default: local # 기본 환경을 local
    include: oauth

  data:
    mongodb:
      host: localhost  #local에서는 'localhost', docker server에서는 'mongodb'로 설정
      port: 27017
      database: metadata
      authentication-database: admin
      username: knuipalab
      password: knuipalab418
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

