spring:
  data:
    mongodb:
      host: mongodb
      username: knuipalab
      password: knuipalab418
      port: 27017
      database: tutorial
      authentication-database: admin
  jpa:
    show-sql: true
  profiles:
    include: oauth
#  main:
#    allow-bean-definition-overriding: true

