version: '3.8'
services:
  middleware:
    build:
      context: ./
      dockerfile: Dockerfile
    
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      innerNetwork:
        aliases:
          - middleware
    depends_on:
      - mongodb
  mongodb: 
    image : mongo
    restart : always
    environment :
      MONGO_INITDB_ROOT_USERNAME: knuipalab
      MONGO_INITDB_ROOT_PASSWORD: knuipalab418
    networks:
      innerNetwork:
        aliases:
          - mongodb
    ports:
     - 27017:27017 
  orthanc:
    image: jodogne/orthanc-plugins:1.5.6
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - '4242:4242' # DICOM
      - '8042:8042' # Web
    networks:
      innerNetwork:
        aliases:
          - orthanc
    restart: unless-stopped
  

networks:
  innerNetwork:
    
      