version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mongodb
      - orthanc
      - middleware
    networks:
      innerNetwork:
        aliases:
          - nginx
  middleware:
    build:
      context: ./DSMP/
      dockerfile: ./Dockerfile
      args:
        - PROFILE=prod
    ports:
      - 8080:8080
    networks:
      innerNetwork:
        aliases:
          - middleware
    depends_on:
      - mongodb
      - orthanc
  mongodb: 
    image : mongo
    volumes:
      # Making the mongo database persistent
      - ./mongoDB/db:/data/db
    restart : always
    environment :
      MONGO_INITDB_ROOT_USERNAME: knuipalab
      MONGO_INITDB_ROOT_PASSWORD: knuipalab418
    networks:
      innerNetwork:
        aliases:
          - mongodb
    # ports:
    #  - 27017:27017 
  orthanc:
    image: jodogne/orthanc-plugins:1.9.7
    volumes:
      # Config
      - ./orthanc/config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Making the Orthanc database persistent
      - ./orthanc/orthanc-db/:/var/lib/orthanc/db/
    # ports:
    #   - '4242:4242' # DICOM
    #   - '8042:8042' # Web
    networks:
      innerNetwork:
        aliases:
          - orthanc
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v2.16.0
    container_name: prometheus
    command:
      - '--web.listen-address=0.0.0.0:9099'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      innerNetwork:
        aliases:
          - prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana:6.6.2
    environment:
      - GF_SECURITY_ADMIN_USER=knuimdc
      - GF_SECURITY_ADMIN_PASSWORD=knuimdc418
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 9900:3000
    depends_on:
      - prometheus
    networks:
      innerNetwork:
        aliases:
          - grafana


networks:
  innerNetwork:
    
      
