version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mongodb
      - orthanc
      - middleware
    networks:
      innerNetwork:
        aliases:
          - nginx
  middleware:
    build:
      context: ./DSMP/
      args:
        - PROFILE=dev
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

    networks:
      innerNetwork:
        aliases:
          - middleware
    depends_on:
      - mongodb
      - orthanc
  mongodb: 
    image : mongo:4.4-rc
    volumes:
      # Making the mongo database persistent
      - ./mongoDB/db:/data/db
    restart : always
    environment :
      MONGO_INITDB_ROOT_USERNAME: knuipalab
      MONGO_INITDB_ROOT_PASSWORD: knuipalab418
    networks:
      innerNetwork:
        aliases:
          - mongodb
    ports:
     - 27017:27017 
  orthanc:
    image: jodogne/orthanc-plugins:1.9.7
    volumes:
      # Config
      - ./orthanc/config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Making the Orthanc database persistent
      - ./orthanc/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - '4242:4242' # DICOM
      - '8042:8042' # Web
    networks:
      innerNetwork:
        aliases:
          - orthanc
    restart: unless-stopped
  

networks:
  innerNetwork:
    
      
